### ISSUE TITLE
Autoloading broken Lots of errors with "v2.4-rails" example

### ISSUE THREAD

**Issue by ksimmi** [karafka/example-apps#530]
Hello,

I cloned this repo and tried to run "v2.4-rails" example and I got an error 
`uninitialized constant KarafkaApp::VisitsConsumer (NameError)`

I fixed it by adding to karafka.rb
```
require_relative 'app/consumers/application_consumer'
require_relative 'app/consumers/visits_consumer'
```

After that I got a new error
```
undefined method `enable!' for Karafka::Web:Module (NoMethodError)
```

I fixed it by adding to karafka.rb
```
require 'karafka/web'
```

After that the example app was started.

**Comment by ksimmi** [comment]
I have to require all classes, such as models, for the code to work.

**Comment by mensfeld** [comment]
please create a reproduction. As far as I use the example app, it works fine (I'm using it as we speak).

**Comment by mensfeld** [comment]
There is no issue with autoloading, class visibility, or anything else (tested now).

If you believe this is an error please create exact reproduction flow for me to run.

ref https://karafka.io/docs/Support/#issue-reporting-guide

**Comment by ksimmi** [comment]
As I mentioned in my first post, I simply cloned the repository, and the problem occurred immediately without any actions on my part. 

I had to use require_relative to run example app. 

I don't know how to reproduce the issue. For me, it occurs immediately.

**Comment by mensfeld** [comment]
I'm sorry but unless you create me a reproducible environment that illustrates this issue (like a docker setup), I will not be investigating this because I git cloned and run this and it works. Feel free to re-open with a **full** reproduction setup that I can use to see the issue.

**Comment by ksimmi** [comment]
I'm trying to create a reproducible environment. But I have problem with `bin/bootstrap` inside the docker.

In the Docker container, the `karafka topics migrate` command ignores the Kafka URL.
my changes in karafka,rb 

```
class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = { 'bootstrap.servers': ENV['kafka_url'] }
```
Console output after `karafka topics migrate`
```
rdkafka: [thrd:127.0.0.1:9092/1]: 127.0.0.1:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
rdkafka: [thrd:127.0.0.1:9092/1]: 127.0.0.1:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
```

For some reason, rdkafka is ignoring  `config.kafka = { 'bootstrap.servers': ENV['kafka_url'] }` and uses 'localhost'

If i will add line with raise:
```
class KarafkaApp < Karafka::App
  setup do |config|
    raise "kafka URL is: #{ENV['kafka_url']}"
    config.kafka = { 'bootstrap.servers': ENV['kafka_url'] }
```

I will get result:
```
docker-compose run web bundle exec karafka topics migrate
Creating karafka-examples_web_run ... done
bundler: failed to load command: karafka (/usr/local/bundle/bin/karafka)
/app/karafka.rb:6:in `block in <class:KarafkaApp>': kafka URL is: kafka:9092 (RuntimeError)
```

docker-compose.yml
```
version: '3.9'

services:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.8.0

    ports:
      - 9092:9092

    environment:
      CLUSTER_ID: kafka-docker-cluster-1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer

  web:
    container_name: example_app_web
    build:
      context: my_api2
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ./my_api2:/app
    ports:
      - 3000:3000
    depends_on:
      - kafka
    environment:
      - RAILS_ENV=development
      - kafka_url=kafka:9092
```
